services:
  altfragen_parser:
    build: ./parser
    container_name: altfragen_parser
    env_file: .env
    volumes:
      - ./parser:/app
    networks:
      - backend

  altfragen_ai:
    build: ./ai-comments
    container_name: altfragen_ai
    env_file: .env
    volumes:
      - ./ai-comments:/app
    networks:
      - backend

  altfragen_subject_worker:
    build: ./ai-comments
    container_name: altfragen_subject_worker
    env_file: .env
    volumes:
      - ./ai-comments:/app
    command: python -m ai_comments.subject_job_worker
    networks:
      - backend
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: caddy_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - /opt/videos:/opt/videos
      - caddy_config:/config
    networks:
      - backend

volumes:
  caddy_data:
  caddy_config:

networks:
  backend:
